eclipse/steady

.gitattributes, docker/README.md, docker/docker-compose.yml, docker/rest-backend/run.sh
This PR:
* Fixes the incorrect name of `rest-backend` which broke the docker-compose
* Makes vulas-docker compatible with Windows by:
* Changing the line endings to LF so that the scripts are runnable by docker
* Change the volumes of postgres to be named, so that no user conflicts will be present. (https://github.com/docker-library/postgres/issues/435)
* Add to the docs a cross-platform way of sharing volumes
Tested on Win10 noWSL - Docker version 18.01.0-ce, build 03596f5
=> Fix docker environment

lang-java-reach/src/main/java/com/sap/psr/vulas/cg/AbstractReachGoal.java, lang-java/src/main/java/com/sap/psr/vulas/java/JarWriter.java, lang-java/src/test/java/com/sap/psr/vulas/java/JarWriterTest.java
I improved Andreas' fix, which only considered the Maven and Gradle case. For CLI, this would have resulted in the deletion of JARs in the `searchPath` folder(s). I tested both with the Maven plugin and the CLI.
=> lang-java-reach: Fixed deletion of rewritten JARs

rest-backend/src/main/resources/db/migration/V20181029.1330__depParentFK.sql
dropping the foreign key on column parent of table app_dependency to avoid performance issues encountered on deletion of applications.
=> added migration to drop parent FK in app_dependency

LICENSE.txt
Updates our License in order to reflect what @msohn said in #47.
I propose to replace `Custom License` with `BSD-like` since on the [Readme of the project](https://github.com/jeantessier/dependency-finder/blob/master/README.md#licensing) it is written that its license is `BSD-like`
=> Update LICENSE.txt/Fixes #47

lang-java/src/test/java/com/sap/psr/vulas/java/JavaIdTest.java
Hi,
We have analysed your codebase and have noticed some gaps in the coverage of JavaId
The following tests for this function has been written with the help of [Diffblue](https://www.diffblue.com/) [Cover](https://static1.squarespace.com/static/5bc9dd6fb2cf795fa3511f70/t/5be2e84f8985836d62e8eb13/1541597264010/Diffblue+Cover+Datasheet.pdf).
Hopefully these tests should help you detect regressions caused by future code changes. Please let us know if you'd be interested in having more tests written for other classes within the vulnerability-assessment-tool and we would be happy to help.
As per your contribution guidelines, both individual and corporate CLAs have been signed and will be sent to the requested addresses asap.
=> Add unit tests to com.sap.psr.vulas.java.JavaId

lang/src/main/java/com/sap/psr/vulas/backend/requests/BasicHttpRequest.java, lang/src/main/java/com/sap/psr/vulas/backend/requests/ConditionalHttpRequest.java
The `*HttpRequest*` classes can be run within or outside the context of analysis goals. In the latter case, the configuration should be obtained with `VulasConfiguration.getGlobal()`, which did not happen.
=> Fixed bug in *HttpRequest* classes related to obtaining the VulasConfiguration

cli-scanner/src/test/java/com/sap/psr/vulas/cli/VulasCliTest.java, lang/src/main/java/com/sap/psr/vulas/backend/BackendConnector.java, lang/src/test/java/com/sap/psr/vulas/goals/BomGoalTest.java, lang/src/test/java/com/sap/psr/vulas/goals/CleanGoalTest.java
The change of `BackendConnector.uploadGoalExecution` done as part of c65c8e48b39a1ba417cecced7544502ac23092f0 led to the situation that the first `APP` goal execution would not have its stats uploaded.
=> Changed goal execution upload such that it works also in case of the 1st app goal execution

lang-java-reach-soot/pom.xml, pom.xml
This PR changes the dependency on the static analysis framework **Soot**, hosted on the Paderborn University Nexus, to the Soot version hosted on Maven Central.
https://search.maven.org/artifact/ca.mcgill.sable/soot/3.3.0/jar
=> Change Soot Dependency to Maven Central

lang-java/src/main/java/com/sap/psr/vulas/java/WarAnalyzer.java, lang-java/src/main/java/com/sap/psr/vulas/java/goals/InstrGoal.java, lang-java/src/main/resources/vulas-java.properties, shared/src/test/java/com/sap/psr/vulas/shared/util/VulasConfigurationTest.java, shared/src/test/resources/vulas-test.properties
If `vulas.core.instr.sourceDir` is not set, JARs and WARs to be instrumented will be searched in `vulas.core.app.sourceDir`. Moreover, the configuration settings `vulas.core.space.token` and `vulas.shared.backend.serviceUrl` will be included in `WEB-INF/lib/lang-java-<version>-jar-with-dependencies-and-config.jar$vulas-core.properties` of instrumented WARs.
=> Fixed instr(umentation) goal

rest-backend/src/main/java/com/sap/psr/vulas/backend/component/ApplicationExporterThread.java
Previously, it was a class member, which probably caused an `ArrayIndexOutOfBoundException` when being called by multiple `ApplicationExperterThread`s
=> Make SimpleDateFormat an instance member

patch-lib-analyzer/src/main/java/com/sap/psr/vulas/patcheval2/PE_Run.java, shared/src/main/java/com/sap/psr/vulas/shared/json/model/Version.java, shared/src/test/java/com/sap/psr/vulas/shared/model/generic/VersionTest.java
Improved compare numeric versions for Version object to also consider the numeric part before trailing strings (e.g., -xyz) instead of only considering the numeric part before dots separators.
Fixed bug when running patch-lib-analyzer without specified the target language
=> improved version comparisons; fix peval w/o lang

docker/docker-compose.yml, docker/haproxy/Dockerfile, docker/haproxy/conf/haproxy.cfg, docker/rest-backend/conf/restbackend.properties, docker/run.sh, docs/public/content/admin/index.md, frontend-apps/src/main/webapp/view/Master.controller.js
- adds restbackend.properties so that we don't display blank info on the frontend
- disables warning for SWID when SWID is not required
- fixes all HAProxy health checks
- creates exporter folders #158 
- removes haproxy.cfg duplication (both COPYied and shared, now only shared) #158 
- shares `.env` file to only selected containers
- removes `spring.datasource.username` and `spring.datasource.password` from `.env` file, now the compose uses directly `POSTGRES_USER` and `POSTGRES_PASSWORD` for restbackend
=> Containers refactor and better experience for users

lang-java-reach/src/main/java/com/sap/psr/vulas/cg/Callgraph.java, lang-java-reach/src/main/java/com/sap/psr/vulas/cg/CallgraphReachableSearch.java, lang-java-reach/src/main/java/com/sap/psr/vulas/cg/NodeMetaInformation.java, lang-java/src/main/java/com/sap/psr/vulas/java/JavaId.java, lang-java/src/main/java/com/sap/psr/vulas/monitor/ClassVisitor.java, lang-java/src/main/java/com/sap/psr/vulas/monitor/slice/SliceInstrumentor.java, lang-java/src/main/java/com/sap/psr/vulas/monitor/trace/TraceCollector.java, lang-java/src/test/java/com/sap/psr/vulas/java/JavaIdTest.java, lang/src/main/java/com/sap/psr/vulas/backend/BackendConnector.java, lang/src/main/java/com/sap/psr/vulas/core/util/CoreConfiguration.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/rest/ApplicationController.java, shared/src/main/java/com/sap/psr/vulas/shared/connectivity/PathBuilder.java
Improvements:
- Traces will not be collected only for executable Java constructs (methods, constructors, static initializers), but also for Java packages and classes.
- A new instrumentor injects code into each and every executable construct which has not been traced before. The injected code looks as follows, it is meant to write an error message and can be configured to throw an `IllegalStateException`:
```
try {
boolean bool = Boolean.parseBoolean(System.getProperty("vulas.core.instr.guard.open"));
System.err.println("Execution of guarded JAVA METH [org.apache.struts.action.ActionFormBeans.getFast()]" + (bool ? "allowed" : "prevented") + " by Vulas guarding condition");
if (!bool) {
throw new IllegalStateException("Execution of guarded JAVA METH …
```
=> Slicing instrumentor and trace collection for Java packages and classes

lang-java-reach-soot/pom.xml
Infoflow depends on `soot:3.2.0`, which has a few dependencies that are not available in Central. Anyhow, those will be discarded due to another dependency on `soot:3.3.0`. As such, in order to prevent problems at the time of the Maven dependency resultion, they are explicitely excluded.
=> Exclude dependencies not available in Central

docs/public/content/css/override.css
squidfunk/mkdocs-material displays multiple times the stars and the forks of the repository if a user reloads the page very fast. This fix hides those copies.
=> Hide superfluous elements wrongly displayed

rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/TracesRepositoryImpl.java
Update application 'lastChanged' flag whenever traces are uploaded. Required to get refreshed data in the frontend when instrumentation is done outside of JUnit tests.
Drawback: When traces are uploaded within JUnit tests by running mvn -Dvulas vulas:prepare-vulas-agent test vulas:upload, 'lastChanged' is updated 3 times: when saving the test and upload goal and while saving the traces. Still, it only impacts 1 application so the overhead should be acceptable.
The current implementation works if it never happens that we save paths without saving traces.
=> refresh of app 'lastChanged' flag when traces are saved

plugin-maven/src/main/java/com/sap/psr/vulas/mvn/VulasAgentMojo.java
If the goal `prepare-vulas-agent` is run without a complete application context being set (using configuration options `vulas.core.appContext.group`, `vulas.core.appContext.artifact` and `vulas.core.appContext.version`), the corresponding values are read from the `pom.xml`.
This behavior has been implemented already for `AbstractVulasMojo` (hence, all other plugin goals), but not yet for `prepare-vulas-agent`.
=> Take GAV from pom.xml if not set before (e.g., via plugin or system property)

lang/src/main/java/com/sap/psr/vulas/core/util/CoreConfiguration.java, lang/src/main/java/com/sap/psr/vulas/report/Report.java, lang/src/main/resources/vulas-core.properties, plugin-maven/src/main/java/com/sap/psr/vulas/mvn/MvnPluginReport.java, shared/src/main/java/com/sap/psr/vulas/shared/util/VulasConfiguration.java
Bug: If the version of the application context is different from the version specified in the `pom.xml`, e.g., because the user specified `vulas.core.appContext.version` explicitily in the Maven command line, the report goal tries to read findings from the backend using the wrong version.
Solution: If the new configuration setting `vulas.report.overridePomVersion` is set to true, the version provided in the `pom.xml` will be overriden with the version of the application context.
=> Allow the overriding of the version of Maven modules for report goal

frontend-apps/src/main/webapp/i18n/messageBundle_en_US.properties, frontend-apps/src/main/webapp/index.html
Improve frontend-apps performances (initial loading time) by:
- asynchronously loading UI5 core library
- [preloading](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content) scripts/stylesheets/fonts
I couldn't preload the `.properties` and `.json` files since those are fetched by UI5 with custom headers and preloading doesn't support custom headers.
=> Frontend performance

rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/ApplicationRepository.java
Modifications in "tests.py " originates a constructChange of type module for the qname "tests" which is too generic (i.e., it's not a unique FQN). Too avoid FPs we exclude it in the query (JOIN) for vulnerable dependencies
- [x ] Tests
=> Exclude tests.py from query for vulndeps

lang-java/src/main/java/com/sap/psr/vulas/monitor/ClassVisitor.java, lang-java/src/main/java/com/sap/psr/vulas/monitor/slice/SliceInstrumentor.java, lang-java/src/main/resources/vulas-java.properties, lang/src/main/java/com/sap/psr/vulas/core/util/CoreConfiguration.java
The whitelist (blacklist) of constructs (not) to be instrumented by the SliceInstrumentor can be read from a file (in addition to populating the blacklist with traced and reachable constructs determined during static and dynamic analysis).
=> Load slicing black and whitelist from files

rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/ApplicationRepository.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/BugRepository.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/LibraryRepository.java
exclude test.__init__ python module from the query for vulndeps as it not "unique enough" to identify the vulnerable artifacts.
=> exclude test.__init__ module from query for vulndeps

rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/AffectedLibraryRepositoryImpl.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/ApplicationRepositoryImpl.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/DependencyRepository.java
PR meant to address issue #225. It also contains a small performance improvements by only looping over dependencies having rebundled libraries which are not the library itself.
=> FP for rebundled libraries

lang-java/src/main/java/com/sap/psr/vulas/java/ArchiveAnalysisManager.java, plugin-maven/src/main/java/com/sap/psr/vulas/mvn/AbstractVulasMojo.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/util/DependencyUtil.java
With release 3.1.0, intra-project dependencies (on other modules of a multi-module Maven project) appeared as parent dependencies in the JSON POSTed to `backend/apps`. Those intra-project dependencies do not necessarily exist in a Maven repository (depending on whether `mvn install` was run beforehand). The result of all this is that the consistency check in `DependencyUtil` failed, hence, the entire upload of applications failed.
The correction consists of suppressing intra-project dependencies as dependency parents.
=> Exclude intra-project dependencies (that point to target/classes rather than an analyzable Java archive)

frontend-apps/src/main/webapp/view/Component.view.xml
until we do not collect also "own" dependencies (deps on modules of the same applications) we cannot show the depth as we do not store the entire list of parents but only the "external ones" (we skip own dependencies)
=> removed depth from UI

lang-java/src/main/java/com/sap/psr/vulas/java/ArchiveAnalysisManager.java, plugin-maven/src/main/java/com/sap/psr/vulas/mvn/AbstractVulasMojo.java
Fixes a bug related to dependencies of type `pom`, which resulted in the failure of application uploads.
=> Only add dependency parents accepted by the ArchiveAnalysisManager

rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/ApplicationRepositoryImpl.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/DependencyRepository.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/LibraryIdRepository.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/LibraryRepository.java, rest-backend/src/test/java/com/sap/psr/vulas/backend/rest/ApplicationControllerTest.java
The query for vulndeps considering vulns affecting bundled libraries was too slow. In the previous implementation the logic was mostly implemented in Java and queries were performed to the db to get the required information, e.g., dependencies w/ bundled libs, libraries corresponding to the rebundled libs (known by GAV), etc.
In this new version, the performance improvement is given by the fact that the logic was pushed to the db using native queries to:
1) directly retrieve the libs (digests) corresponding to GAVs rebundled in some dependencies of an application
2) directly retrieve the library ids (gavs) corresponding to those rebundled in some dependencies of an application
=> improved performances for vulns in bundled libs

shared/src/main/java/com/sap/psr/vulas/shared/util/FileUtil.java, shared/src/test/java/com/sap/psr/vulas/shared/util/FileUtilTest.java
Fix a case that FileUtil.getFileName returns a wrong file name without an extension if a name contains dots.
**Input:** /project/js/hello.io.min.js
**Expression:** FileUtil.getFileName("/project/js/hello.io.min.js", false);
**Expected Output:** hello.io.min
=> fix(shared): handle a case of file name with dots

patch-lib-analyzer/src/main/java/com/sap/psr/vulas/patcheval/utils/CSVHelper2.java, patch-lib-analyzer/src/main/java/com/sap/psr/vulas/patcheval2/BugLibManager.java
Added to patch-lib-analyzer to propagate existing manual assessments (affected=false) for bug w/o construct changes (until now it was done for bug w/ construct changes even if no MOD methods/constructors was present). The propagation is done for library ids whose version:
- is greater than the one of a library ids assessed as NOT affected,
- and is not smaller than the one of a library ids assessed as affected.
=> Propagate manual assessments for bugs w/o changes

shared/src/main/java/com/sap/psr/vulas/shared/json/model/Dependency.java
The existing compareTo was not properly handling dependencies with same filename but different LibraryId (and thereby residing in different paths). As a consequence just one was added to the list of dependencies of an application and if the one left out was used as a parent an invalid Json was posted to the backend.
The new compareTo ensures that both dependencies are added to the application's dependency list
- [ x] Tested locally
=> added comparison on path to Dependency.compareTo

patch-lib-analyzer/src/main/java/com/sap/psr/vulas/patcheval2/BugLibManager.java, patch-lib-analyzer/src/main/java/com/sap/psr/vulas/patcheval2/PE_Run.java
Improved patch-lib-analyzer to skip a single vulnerability (and proceed to analyze the remaining) in case anything goes wrong while connecting to the backend and lib-utils services.
=> in case of backend exception; proceed with next vuln

rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/LibraryIdRepository.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/rest/LibraryIdController.java
The LibraryIdController when used to get vulnerable/non-vulnerable libraryIds, was not considering vulnerabilities in rebundled LibIds. As a consequence the mitigation tab of the web frontend would show as non-vulnerable a GAV that actually has vulnerabilities in some rebundled library.
=> Check for vuln in rebundled libids querying from LibraryIdController

docker/docker-compose.yml, docker/haproxy/Dockerfile, docker/postgresql/Dockerfile, docker/push-images.sh, docs/public/content/admin/tutorials/docker.md, docs/public/content/admin/tutorials/registry.md
We now use directly `haproxy` and `postgres` images and we use `volumes` and `command`s to tune the container.
This contribution is toward automatically push images on Docker Hub.
=> Removes the generation of postgres/haproxy images

.travis.yml, docker/.env.sample, docker/docker-compose.build.yml, docker/docker-compose.yml, docker/push-images.sh, docs/mkdocs.yml, docs/public/content/admin/index.md, docs/public/content/admin/tutorials/build.md, docs/public/content/admin/tutorials/docker.md, docs/public/content/admin/tutorials/registry.md
Since we now have our images on Docker Hub. It's easier for users to deploy `vulnerability-assessment-tool`, they don't need anymore to build the images locally, they just pull the official ones.
We now thus have two `docker-compose` files. One that uses the pushed images and one that builds locally.
=> Docker deployment rework

docs/public/content/user/manuals/assess_and_mitigate.md
Updated the documentation in order to describe how-to fix Uber JARs that contain (rebundle) the vulnerable code of a dependency.
=> Added a description on how-to fix Uber JARs with vulnerable code

repo-client/src/main/java/com/sap/psr/vulas/git/GitClient.java
Use `_rev.split(":")` to splits String `_rev` in `getFileChanges` method when it contains revision hash and branch tag.
This change will fix the bug that `GitClient` does not create a new directory with the full revision hash (40 characters).
=> fix(repo-client): GitClient splits rev:branch

lang-java/src/main/java/com/sap/psr/vulas/java/JarAnalyzer.java, lang-java/src/main/java/com/sap/psr/vulas/java/tasks/JavaBomTask.java, lang/src/main/java/com/sap/psr/vulas/goals/BomGoal.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/util/DependencyUtil.java
The dependency list of an application (including parents information) must conform two main rules:
- parents must be included in the main set
- each dependency in the main set must occur only once.
Currently, the elements which differentiate dependency are : digest, parent, and relativePath.
The existing client is not populating the relativePath but only the path, as a result it may happen that the backend return HTTP 500 in case two dependencies in the main set have same digest and parent null (even if the path differs as we currently use the relativePath to differentiate).
Alternatives to be discussed:
- add use of relative path in the client
- remove dependency with same digest, parent and relativePath before upload (we loose some details but the upload will succeed)
- use the path to …
=> fix dependency structure

.travis.yml, rest-backend/pom.xml, rest-backend/src/main/java/com/sap/psr/vulas/backend/cve/CveReader2.java, rest-lib-utils/pom.xml
Since the Maven modules `rest-backend` and `rest-lib-utils` do not inherit from root, the profiles to generate JavaDoc, PGP sign and release to Maven Central had to be copied into their respective `pom.xml`.
=> Modified pom.xml of rest-backend and rest-lib-utils

.travis.yml, .travis/docker_hub_push_release.sh, .travis/docker_hub_push_snapshot.sh, .travis/settings.xml, pom.xml, rest-backend/pom.xml, rest-lib-utils/pom.xml
This fixes the issue on the master branch with skaffold being unable to find `jib` prefix when building the jib container images by adding a pluginGroup to the settings.xml in the .m2 folder. Skaffold successfully builds images (the push procedure still needs to be tested using the official credentials)
=> Add jib plugin to the maven settings.xml

lang/src/main/java/com/sap/psr/vulas/goals/ReportGoal.java, lang/src/main/java/com/sap/psr/vulas/report/Report.java
This fix improves the error handling of the report goal. When vulnerable dependencies cannot be downloaded, the report creation aborts.
=> Throw exception and stop report generation if vulns cannot be downloaded

shared/pom.xml
Remove the direct dependency of module `shared` on `commons-beanutils`.
=> Removed commons-beanutils from shared

docs/public/content/user/manuals/setup.md, lang/src/main/java/com/sap/psr/vulas/report/Report.java, lang/src/main/resources/vulas-core.properties, rest-backend/src/main/java/com/sap/psr/vulas/backend/model/Application.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/rest/HubIntegrationController.java, rest-backend/src/test/java/com/sap/psr/vulas/backend/rest/HubIntegrationControllerTest.java, rest-backend/src/test/resources/dummy_app/lib_bar.json
Use the query string param `ignoreUnassessed` to specify whether un-assessed vulnerabilities are exported. Un-assessed vulns are those where the method signature(s) of a bug appear in an archive, however, it is yet unclear whether the methods exist in the fixed or vulnerable version. Those findings are marked with an orange hourglass in the frontend. 
The behavior of the config is similar to that of the `report` goal in regards to whether a build exception is thrown.
Possible values:
- `all`: All un-assessed vulns will be ignored
- `known`: Only un-assessed vulns in archives known to Maven Central will be ignored
- `off` (default): Never ignore (old behavior)
=> Added config parameter to HubIntegrationControler.getExportItem(...)

rest-backend/src/main/java/com/sap/psr/vulas/backend/model/Space.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/model/Tenant.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/rest/HubIntegrationController.java, rest-backend/src/test/java/com/sap/psr/vulas/backend/rest/HubIntegrationControllerTest.java
The endpoint `/hubIntegration/apps/{itemId:.+}/vulndeps` now checks whether the given export item (space or app) is indeed part of the tenant (the default one or the one specified with `X-Vulas-Tenant`). If not, the endpoint returns `400` (bad request).
=> Check that export item belongs to the tenant in question, fail if not

frontend-apps/src/main/webapp/view/BugDetail.controller.js, rest-backend/src/main/java/com/sap/psr/vulas/backend/rest/ApplicationController.java
This fixes #230, which occurs when requesting the reachability graph for a construct whose signature contains special characters such as `[` or `]`.
=> Urlencode construct signatures

kubernetes/helm/utils/go.sum, kubernetes/helm/utils/internal/load/load.go, kubernetes/helm/utils/pkg/connect/client.go
This commit allows for clients to use the `vulas-utils` utility for managing their kubernetes cluster on any provider (GCP, AWS, Azure etc...).
=> GCP integration fix

docs/public/content/user/manuals/analysis.md, docs/public/content/user/manuals/setup.md
This change describes how to export findings for single applications. So far, the documentation only covered entire workspaces.
=> Improve documentation for data export

docker/push-images.sh
Added latest tag to docker images pushed to docker hub.
This can also be done in a more concise way, that would make distinguishing the failure between two push phases impossible:
```sh
IMAGE=${REGISTRY}/${PROJECT}/vulnerability-assessment-tool-${service}
docker tag vulnerability-assessment-tool-"${service}":"${VULAS_RELEASE}" "${IMAGE}:latest" vulnerability-assessment-tool-"${service}":"${VULAS_RELEASE}" "${IMAGE}:${VULAS_RELEASE}"
docker push "${IMAGE}:${VULAS_RELEASE}"
```
=> Add latest tag to docker images

rest-backend/src/main/java/com/sap/psr/vulas/backend/rest/CveController.java, rest-backend/src/test/java/com/sap/psr/vulas/backend/rest/BugControllerTest.java
Added new endpoint `/cves/refreshCache/{id}` to update the cached CVE data of a single bug.
=> Added new endpoint to refresh the cached CVE data of a single bug

rest-lib-utils/src/main/resources/vulas-rest-lib-utils.properties
[Maven Central now requires HTTPS and forbids HTTP](https://support.sonatype.com/hc/en-us/articles/360041287334), which required to change a couple of URLs in the properties of `rst-lib-utils`
=> Changed Maven URLs from http to https

plugin-maven/src/main/java/com/sap/psr/vulas/mvn/VulasAgentMojo.java
The Maven goal `prepare-vulas-agent` takes configuration settings and includes them in the Surefire argument `argLine`. If too many configuration settings are considered, this will lead to the Surefire error "The command line is too long". To prevent this, all exemption-related settings will not be included any more in `argLine`, they are anyways not needed during the instrumentation.
=> Omit vulnerability exemptions in Surefire argLine setting

rest-backend/src/main/java/com/sap/psr/vulas/backend/model/Dependency.java, rest-backend/src/main/resources/db/migration/V20200219.1130__dropDepIndexes.sql
The 500 error was raised whenever CLEAN or APP was run on an application having multiple dependencies on the same library (same digest) having different parents. This probably happens with multi module applications where a module appears as direct dependency of another module and thus if APP is run without a CLEAN, the transitive dependencies gets duplicated with the newly built module as parent.
In such situation, before deleting the dependencies that do not exist any longer (all in the case of a CLEAN), JPA triggers an SQL update on such dependencies to set the parent to null. 
This causes a constraint violation exception as we enforced at db level that app and lib must be unique whenever the parent and relativePath are null.  
This constraint was created (together with other 2 …
=> Avoid HTTP 500 error during CLEAN and APP goals

docs/checklinks.sh
Unified timeout duration in checklink.sh and increased it to 80.
This may increase the overall time of the docs build phase if an URL is broken but is worth it because it helps avoid random failure of the build process.
_Duplicated PR due to requirement that all commit are signed_
=> increase muffet url timeout

docs/public/content/user/tutorials/java_gradle.md
The Gradle tutorial and configuration snippets could be shortened now that Steady artifacts are available on Maven Central.
=> Updated Gradle tutorial

.travis.yml
The docker tag release did not work from 3.1.4 as the parameters and regex were wrong which is fixed with this PR.
=> Fix Travis tag docker release

rest-backend/src/main/java/com/sap/psr/vulas/backend/model/Application.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/ApplicationRepositoryImpl.java, rest-backend/src/test/java/com/sap/psr/vulas/backend/rest/ApplicationControllerTest.java
Bug observed:
The exception
"EntityNotFoundException: Unable to find com.sap.psr.vulas.backend.model.Dependency with id XYZ"
was triggered when retrieving an application from the db in case the parent of a dependency contained the id of a dependency not existing anylonger. The DB allowed such a case as we removed the foreign key between the column parent and the dependency table for performance reasons.
What do we know:
Most likely, this bug is due to the way we were saving dependencies which relied on the db. To link a dependency to its parent, the latter needs to exists so that the link can be established based on the hibernate id. To save the dependencies we were using the "save" method of the CrudRepository, Later on, when setting the parents, we were looking in the db (via a JPQL …
=> Fix missing dependency on parent

lang-java/src/main/java/com/sap/psr/vulas/java/ArchiveAnalysisManager.java, lang/src/main/java/com/sap/psr/vulas/backend/requests/ConditionalHttpRequest.java, lang/src/main/java/com/sap/psr/vulas/malice/ZipSlipAnalyzer.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/ApplicationRepositoryImpl.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/BugRepositoryImpl.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/LibraryRepositoryImpl.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/SpaceRepositoryImpl.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/TenantRepositoryImpl.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/rest/ApplicationController.java
Following the possibility to better configure the log level threshold with system property `vulas.log4j.threshold` (#339), this PR is used to adjust the level of logging statements both in client and server components.
=> Adjust log levels

rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/AffectedLibraryRepository.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/AffectedLibraryRepositoryCustom.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/AffectedLibraryRepositoryImpl.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/rest/BugController.java, rest-backend/src/test/java/com/sap/psr/vulas/backend/rest/BugControllerTest.java
This PR enhances the rest endpoint GET /bugs/{bugId}/affectedLibIds. This endpoints returns all affectedLibraries for a given bug. However, in the case of affected libraries linked to libraryIds (GAVs), it may be the case that the GAVs is associated to libraries (digests) that are not publicly available, i.e., that are not well known (In the steady implementation, the field wellknownDigest is true if the archive digest is known in the configured maven repository, Maven Central by default).
The newly added querystring parameter 'onlyWellknown' allows to get affectedLibraries for the set of library ids that are linked to libraries that have the flag wellknownDigest=true.
=> Get affected libraries for well known artifacts

rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/LibraryRepository.java
This PR modifies the native query that select bundled libraries. Given an application, the query returns pairs dependency, (bundled) library. 
Problem observed:
Vulnerabilities reported ONLY for a bundled GAVs equal to the GAV of the dependency itself. E.g., CVE1 reported for GAV org.a:project-b:0 bundled  in dependency org.a:project-b:0, but not for the dependency org.a:project-b:0 itself.
Why it happens:
When we select from the DB pairs (dependency, library), we only ensure that the digest of the dependency and of the bundled library are different. We then create instances of VulnerableDependency for the pair dependency and bug associated to the bundled library. As the GAV of the dependency itself is usually part of the set of bundledLibraries, the bug affecting the dependency itself …
=> Restrict condition for bundled Libraries

rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/AffectedLibraryRepositoryImpl.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/ApplicationRepositoryImpl.java
The Internal Server Error "Missing Dependency with id XYZ" is still occurring as PR #355 didn't solve the problem entirely (it mainly prevents the multiplication of dependencies).
The error occurs when several scans of the same application are run in parallel. It can be reproduced triggering several time the HTTP requests corresponding to the goals CLEAN and APP. In particular, it consistently occur when running 7 times the pair of calls to clean (POST) and save the app (PUT).
The "missing dependency" issue occurs at the end of the parallel calls, whereas during their execution we get different exceptions: constraint violation on app_constricts_pk (when saving the same application in parallel) and optimisticLocking exception (when saving entities that were updated or deleted in parallel). …
=> Fix (again) missing parent dependency

LICENSE.txt
Following the request from Eclipse's legal time, one paragraph from `LICENSE.txt` has been removed. It referred to the potential use of SAP APIs, and has been added by default when going open source in 2018. However, given that no SAP APIs are used, and since the project moved to the Eclipse Foundation, this paragraph is no longer necessary. Moreover, `LICENSE.txt` has also been updated to reflect the use of the 3rd party component p-queue.
=> Removed API section from LICENSE.txt, and added reference to 3rd party component p-queue

rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/ApplicationRepositoryImpl.java
Added transactional annotation to the retrieval of vulnerable dependencies to avoid ObjectNotFoundException when retrieving objects from the db by Id. The exception would occur in the case of parallel executions where one scan retrieves vulnerable dependencies and another saves application dependencies (altering the ids).
Note.
The observed exception occurred in line 532 of ApplicationRepositoryImpl.java:
=> Transactional retrieval of vulnerable dependencies

docs/requirements.txt
Signed-off-by: Sumeet Patil <sumeet.patil@sap.com>
Specifying versions for mkdocs
- With default pip install all the new versions are installed
- New versions introduce lot inconsistencies and errors in the github pages
- New release changes - https://squidfunk.github.io/mkdocs-material/releases/5/
- This is a quick fix. But the permanent fix will be to adapt to version 5
=> Specifying versions for mkdocs

rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/TracesRepository.java
Problem: Vulnerability shown as traced in the overview (red paw) but none of the construct are shown as traced in the vulnerbility details.
Analysis:
Since version 3.0.18, the client also traces (and uploads) constructs of type PACK and CLAS. However those must not be used to compute the traced flag at the level of the vulnerability (resulting in the red paw in the vulnerability overview table).
=> Exclude PACK and CLAS from traced flag

frontend-bugs/src/main/webapp/model/Config.js, frontend-bugs/src/main/webapp/view/Component.controller.js, frontend-bugs/src/main/webapp/view/Master.controller.js, lang/src/main/java/com/sap/psr/vulas/backend/requests/BasicHttpRequest.java, shared/src/main/java/com/sap/psr/vulas/shared/util/VulasConfiguration.java, shared/src/test/java/com/sap/psr/vulas/shared/util/VulasConfigurationTest.java
POST and PUT calls of the BugController shall be protected through a dedicated, configurable token.
This token has to be added as HTTP header by all Java clients (kb-importer, patch-analyzer, patch-lib-analyzer) and by the bug frontend (frontend-bugs). The Java clients just require a corresponding configuration parameter (`vulas.shared.backend.header.<key>`) in order to include the HTTP header.
The HAProxy configuration has to be adjusted to check the configurable token for all HTTP PUT and POST requests to `.../backend/bugs/...`.
=> Protect PUT and POST endpoints of the BugController

lang/src/main/resources/vulas-core.properties
Reverting default for unassessed bugs to 'all' (config vulas.report.exceptionExcludeUnassessed)
=> default for unassessed bugs in report set to all

.travis.yml, .travis/package_steady_cli.sh
- The cli release was failing because some point of time the build artifacts were getting cleared. So changed it to wget, where we get the artifacts online
- The docs release was causing permission issues. Hence, added --user and used python3
=> Fix docs and cli release

rest-nvd/app/main.py
Currently, any request to `nvd/vulnerabilities/<cve-id>`
returns a response with the headers
```
Content-Type: application/json
Content-Type: application/json; charset=utf-8
```
Since flask since version 1.1.0 automatically sets the `Content-Type: application/json`
see https://flask.palletsprojects.com/en/1.1.x/quickstart/#apis-with-json
The code
`return data, 200, {'Content-Type': 'application/json; charset=utf-8'}`
results in the duplicate Content-Type header. 
This PR fixes the duplicate code.
=> Fix: Duplicate content-type header in NVD-rest

rest-nvd/Dockerfile
Hi all,
this changes the order of layers in the `rest-nvd`'s `Dockerfile` so to cache and reuse them even when the business logic inside `/app` has changed
I have also some suggestions:
- better to declare all the requirements in the `setup.py` and get rid of the `pip install plac tqdm  requests` step in the `Dockerfile`
- @henrikplate, shouln't we update all the `LABEL maintainer="Vulas vulas-dev@listserv.sap.com"`s of our `Dockerfile` to something more Eclipsy?
- you can try to use the `alpine` version of `tiangolo/meinheld-gunicorn-flask` so to be a bit more `secure` and `fast`.
- maybe you can upload the image to the Docker Hub, I guess some people could benefit
- [pin](https://stackoverflow.com/a/8161816/3482533) the version of the deps in the `setup.py`
=> Change order of layers for `rest-ndv`'s Dockerfile

lang-java/pom.xml, lang/pom.xml, lang/src/main/java/com/sap/psr/vulas/backend/requests/BasicHttpRequest.java
This PR is raised to change the standard JDK HttpURLConnection to the Apache Http client. This is done to send keep-alive probes. Changing it to Apache Http Client enables users to configure keep-alive probes by changing OS parameters like net.inet.tcp.keepidle, net.inet.tcp.keepintvl and net.inet.tcp.keepcnt.
**Working process of these OS params** 
1. The client opens a TCP Connection
2. If the connection is silent for net.inet.tcp.keepidle(tcp_keepalive_time) seconds, send a single empty ACK packet
3. Did the server respond with a corresponding ACK of its own?
-  **YES** - > Return to step 2
-  **NO**  - > Wait net.inet.tcp.keepintvl(tcp_keepalive_intvl) seconds, then send another ACK. Repeat until the number of ACK probes that have been sent equals …
=> Change Http Client

docs/public/content/user/manuals/analysis.md
This PR updates the links of our docs towards Soot. Apparently they've changed the name of their Github Org.
https://github.com/soot-oss/soot not `sable` anymore
The second link could be updated to https://www.sable.mcgill.ca/soot/ (note the `https`) but that page is 8 years old, so maybe it's better to point both links to the latest Soot docs page.
=> Soot dead links

rest-backend/src/main/java/com/sap/psr/vulas/backend/model/Library.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/LibraryRepositoryImpl.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/util/DigestVerifier.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/util/DigestVerifierEnumerator.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/util/MavenCentralVerifier.java, rest-backend/src/main/java/com/sap/psr/vulas/backend/util/PyPiVerifier.java, rest-backend/src/test/java/com/sap/psr/vulas/backend/rest/BugControllerTest.java, rest-backend/src/test/java/com/sap/psr/vulas/backend/rest/HubIntegrationControllerTest.java, rest-backend/src/test/java/com/sap/psr/vulas/backend/rest/LibraryControllerTest.java, rest-lib-utils/src/main/java/com/sap/psr/vulas/cia/util/ArtifactDownloader.java, rest-lib-utils/src/main/java/com/sap/psr/vulas/cia/util/ClassDownloader.java, rest-lib-utils/src/main/java/com/sap/psr/vulas/cia/util/MavenCentralWrapper.java, shared/src/main/java/com/sap/psr/vulas/shared/json/model/mavenCentral/MavenSearchResponse.java, shared/src/main/java/com/sap/psr/vulas/shared/json/model/mavenCentral/MavenVersionsSearch.java, shared/src/main/java/com/sap/psr/vulas/shared/json/model/mavenCentral/ResponseDoc.java
When libraries are saved, the backend checks whether the digest is wellKnown using one of the implemented verifiers, i.e. Maven Central and Pypi.
Problem Observed:
Until now we didn't check whether the libraryId provided by the client is also well known, as a result we may end up with not-well-known library ids saved to the database (even for well known digests).
Solution:
The verifyDigest method now checks that the provided libraryId is wellKnown, and replaces it with the well known one if it isn't (it takes the first in case multiple ones are returned). Note that:
- the verification is not done in the prePersist method anylonger because we need to save the transient LibraryId entity in case it gets replaced.
- the verification now happens every time a library is saved (thus replacing …
=> Check if Library Id (GAV) is well known

rest-backend/src/main/resources/db/stats.sql
The SQL script added with this pull request computes the following simple usage metrics:
- the number of distinct projects (having distinct group IDs)
- the number of active projects (with goal executions in a given time frame)
- the number goal executions of a given type in a given time frame
=> Added SQL script to compute few simple metrics

plugin-maven/pom.xml, rest-lib-utils/pom.xml
Updated then dependencies of plugin-maven and rest-lib-utils. The latter dependency resulted from the use of dependency-finder, and required to update the Maven groupId from `ant` to `org.apache.ant`.
=> Updated ant to 1.10.8

lang/src/main/java/com/sap/psr/vulas/backend/requests/BasicHttpRequest.java
setExpectContinueEnabled is added to get rid of broken pipe exception. 
The PUT/POST is sent with a huge payload with the header X-Vulas-Token. If the Token is invalid the server quickly closes the connection, the client still tries to send a payload even when the connection was closed at the server end which causes broken pipe exception. Expect Continue is introduced in HTTP 1.1 and handles this well as it just sends the headers and tries to validate if there is any failure, if there is no failure it sends the whole payload.
ExpectContinue is part of HTTP 1.1 spec
More details - https://hc.apache.org/httpclient-3.x/apidocs/org/apache/commons/httpclient/methods/ExpectContinueMethod.html
=> Show error on wrong token

rest-backend/src/main/java/org/eclipse/steady/backend/repo/AffectedLibraryRepositoryImpl.java, rest-backend/src/main/java/org/eclipse/steady/backend/repo/ApplicationRepositoryImpl.java, rest-backend/src/test/java/org/eclipse/steady/backend/rest/ApplicationControllerTest.java
In case of vulnerabilities for bundled libraries (both vulnerabilities with and without code changes), affected libraries defined for the library (digest) of the outer libraries (i.e. the dependency containing the vulnerable library) were not considered. Only affected libraries defined for the outer libraryId (GAV) were kept into account.
=> consider affected libraries for outer library digest

cli-scanner/pom.xml, kb-importer/pom.xml, patch-analyzer/pom.xml, patch-lib-analyzer/pom.xml
Steady clients kb-importer, patch-analyzer, and others were failing with Java 9 (and later releases).
This is because log4j-api 2.9.1 and above are packaged as a multi-release JAR and support the use of the StackWalker and Process APIs. But the Steady clients do not support muti-release JAR due to which the clients fail with errors. 
The changes in this PR will add muti-release JAR support for Steady clients (by adding the manifest file entry `Multi-Release: true` to self-contained Uber-JARs).
=> Fix for multi release log4j jar

cli-scanner/pom.xml, kb-importer/pom.xml, patch-analyzer/pom.xml, patch-lib-analyzer/pom.xml, pom.xml
Added manifest file entry `Multi-Release` to all Java artifacts
=> Added support for multi release

kb-importer/src/main/java/org/eclipse/steady/kb/task/ImportVulnerability.java
Changed the API to escape JSON characters. Formerly used `StringEscapeUtils.escapeJavaScript` escapes single quote characters, which is not required for JSON.
=> Fix escaping of JSON description

kb-importer/src/main/resources/log4j.properties, shared/src/main/resources/log4j2.xml
Some message contains date formats which have to be logged as it is. Log4j tries to parse such dates and throws an exception when there are invalid date formats.
Example log which contains **simple(\"myfile-${date:now:yyyyMMdd}.txt\"))** - 
```
MOD JAVA METH [org.apache.camel.component.file.FileConsumerFileExpressionTest.testConsumeFileBasedOnDatePattern()]
F_AST :{"ast":[{"Value":"testConsumeFileBasedOnDatePattern","SourceCodeEntity":{"Modifiers":"0","SourceRange":{"Start":"19","End":"1194"}},"EntityType":"METHOD","C":[{"Value":"template.sendBodyAndHeader(\"file://target/filelanguage/date\", \"Bye World\", Exchange.FILE_NAME, \"myfile-20081128.txt\");","SourceCodeEntity":{"Modifiers":"0","SourceRange":{"Start":"87","End":"204"}},"EntityType":"METHOD_INVOCATION"},{"Value":"template.sendBod …
```
=> Fix logging for messages which contain invalid date formats

pom.xml, set-version.sh
Updated plugins to versions that support [reproducible builds](https://reproducible-builds.org/docs/jvm/).
Added script to facilitate the bumping of versions before and after a release.
Check reproducibility of distributed maven artifacts with
```
mvn clean install -e -DskipTests
mvn clean verify -e -DskipTests artifact:buildinfo
```
More information at
- https://maven.apache.org/guides/mini/guide-reproducible-builds.html
- https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74682318.
=> Make builds of distributed Maven artifacts reproducible

kb-importer/src/main/java/org/eclipse/steady/kb/util/ConstructSet.java
[REUSE](https://api.reuse.software/info/github.com/eclipse/steady) shows the batch is non-compliant. 
The issue was with ConstructSet.java which is fixed with this PR.
=> fix: REUSE compliance

docker/kb-importer/start.sh
This fix is for Mac and Windows. Docker does not have native support for Mac and Windows. Docker volumes work very slow on Mac and Windows.
The workaround for now is removing the volumes of kb-importer and running the docker containers -
```
- "./kb-importer/data:/kb-importer/data:delegated"
- "./kb-importer/tmp:/tmp:delegated"
```
=> Fix kb-imorter for Mac and Windows

lang/pom.xml
Changed velocity dependency to remove CVE-2020-13936
=> Changed velocity 1.7 to velocity-engine-core 2.3

lang/src/main/java/org/eclipse/steady/report/Report.java, lang/src/main/resources/velocity_template.html, lang/src/main/resources/velocity_template.json, lang/src/main/resources/velocity_template.xml
Velocity template variables `$vulas-shared-homepage` and `$vulas-backend-serviceUrl` were not any more populated when generating the report. This regression was probably introduced with commit  ff4c80ad54f513153d05d1fbaf4b475f3957309f, when switching from Velocity version 1.7 to 2.3. According to the [Velocity Template Language](https://velocity.apache.org/engine/2.3/vtl-reference.html), hyphens are not anymore allowed for identifiers (by default).
Using camel case solves the issue.
=> Changed Velocity variable names

docs/public/content/user/manuals/analysis.md, lang-java-reach-soot/pom.xml, lang-java-reach-soot/src/main/java/org/eclipse/steady/cg/soot/CustomEntryPointCreator.java, lang-java-reach/pom.xml, lang-java-reach/src/main/resources/vulas-reach.properties, lang-java/pom.xml, pom.xml
Upgraded Soot from 3.3.0 to 4.1.0 to perform the reachability analysis on Java versions greater than 8, and made Soot the default call graph construction framework by setting `vulas.reach.fwk = soot`
=> Updated Soot and it the default callgraph construction fwk

.pipeline/config.yml, Jenkinsfile, pom.xml, repo-client/pom.xml, rest-backend/pom.xml, rest-lib-utils/pom.xml
Updated the `maven-gpg-plugin` from version 1.5 to 3.0.1, and added condition to GPG sign and deploy on Maven Central upon the creation of `release-*` tags.
=> Updated maven-gpg-plugin and added condition on tag name to trigger deployments on Maven Central

rest-lib-utils/src/main/java/org/eclipse/steady/cia/util/MavenCentralWrapper.java
The addition of  a timeout to the rest requests to Maven central is meant to mitigate #183  by avoiding waiting for the gateway timeout (HTTP 504)
=> Added timeout to rest_template for Maven Central

.gitignore, Jenkinsfile, frontend-apps/pom.xml, frontend-bugs/pom.xml, patch-lib-analyzer/pom.xml, plugin-gradle/build.gradle, plugin-gradle/pom.xml, pom.xml, rest-backend/pom.xml, rest-lib-utils/pom.xml, shared/pom.xml
Added [`maven-artifact-plugin`](https://maven.apache.org/plugins/maven-artifact-plugin/buildinfo-mojo.html) to create build information in `target/*.buildinfo` and compare whether Java archives created in two subsequent builds are bit-identical (only those with property `maven.deploy.skip=false`, thus, those that will be deployed on Maven Central). In case of differences, the build breaks in stage "Verify JavaDoc, Source and Reproducibility".
=> Make builds reproducible and add corresponding check in Jenkins pipeline

pom.xml
Configured the `flatten-maven-plugin` to keep POM elements required for uploads to Maven Central, and the `nexus-staging-maven-plugin` to skip the deployment of certain modules on Maven Central.
=> Fixed configuration of flatten and nexus plugin

Jenkinsfile
Increase limits to prevent sudden pipeline death (exit code 137)
=> Increase limits to prevent sudden pipeline death (exit code 137)

kb-importer/pom.xml
Updated json-path to get off a vulnerable version of json-smart
=> Updated json-path from 2.4 to 2.6 in order to update json-smart

lang-java-reach-soot/pom.xml, plugin-maven/pom.xml, pom.xml
Updated org.apache.maven:* dependencies from 3.8.1 to 3.8.2, ant from 1.10.10 to 1.10.11, and soot-infoflow from 2.8 to 2.9.0.
The update of org.apache.maven resulted in a new dependency on org.codehaus.plexus:plexus-cipher 1.8, which replaces org.sonatype.plexus:plexus-cipher (a transitive dependency of org.apache.maven:maven-core 3.8.1 that has been [removed with version 3.8.2](https://github.com/apache/maven/commit/24da558d5a1714f5e2427ed73e8f139168128a30)).
=> Updated org.apache.maven dependencies from 3.8.1 to 3.8.2

Jenkinsfile, docker/docker-compose-new.yml, docker/setup-steady.sh, docker/start-steady.sh, rest-lib-utils/src/test/java/org/eclipse/steady/cia/rest/IT03_ClassControllerTest.java
To further control the footprint of the Docker Compose application, a new profile called VDB was introduced.
By now, the following service profiles exist in `docker/docker-compose-new.yml`:
- **core** services: `haproxy`, `rest-backend` and `postgresql` need to always run
- **UI** services: `frontend-apps`, `frontend-bugs` and `cache` deliver OpenUI5 Web applications for scan results (http://localhost:8033/apps) and vulnerabilities (http://localhost:8033/bugs).
- **VDB** services: `rest-lib-utils`, `kb-importer` and `patch-lib-analyzer` update the vulnerability database and resolve un-assessed findings (by comparing method bodies obtained from `rest-lib-utils`)
=> Introduced vdb profile in Docker Compose application

LICENSE
`LICENSE` in the project's root directory was a symlink to `LICENSES/Apache...`, to comply with [REUSE's requirement](https://reuse.software/spec/#license-files) to have all license files below the LICENSES directory.
However, the symlink was not consistently handled by the GitHub API, hence, the API reported that Steady has an unknown license, which led to one of the problems described in https://github.com/todogroup/ospolandscape/issues/97.
Details:
- Some GitHub API endpoints properly resolve the symlink and deliver the content of the link target as base64. In particular, this holds true for the Licenses API: https://api.github.com/repos/eclipse/steady/license
- However, this content is not looked at to populate the license property of the result JSON (both Licenses API and Repos API): …
=> Replaced LICENSE symlink by actual file

lang-java/pom.xml
`com.google.inject.extensions:guice-assistedinject` was downgraded from `5.0.1` to `4.2.3`, due to an API incompatibility within `changedistiller`.
=> Downgrade guice due to API incompatibility (changedistiller)

pom.xml, rest-lib-utils/pom.xml
Updated `org.apache.ant:ant` from version 1.10.10 to 1.10.11, as well as `log4j-api` and `log4j-core` from 1.14.1 to 1.15.0.
=> Update vulnerable versions of log4j and ant

rest-backend/pom.xml
Updated `com.google.guava:guava` from vulnerable version 28.2-jre to fixed version 30.0-jre
=> Update vulnerable version of guava

pom.xml
Updated log4j from vulnerable version 2.15.0 to 2.16.0
=> updated log4j to 2.16.0

bump-version.sh, docker/.env.sample
Corrected version in `.env.sample`, which is taken by the setup script, and updated `bump-version.sh` to make sure this happens automatically in the future.
=> Change version in .env.sample and fix bump script

pom.xml, rest-backend/pom.xml
Updated Log4j from 2.17.0 to 2.17.1, changed scope of H2 from compile (default) to test.
=> Updated Log4j from 2.17.0 to 2.17.1, changed scope of H2 from compile (default) to test

rest-backend/pom.xml, rest-backend/src/main/java/org/eclipse/steady/backend/repo/AffectedLibraryRepository.java, rest-backend/src/main/java/org/eclipse/steady/backend/repo/LibraryRepository.java, rest-backend/src/main/resources/application-docker.properties, rest-backend/src/main/resources/application-localhost.properties, rest-backend/src/main/resources/application-test.properties
Updated rest-backend to depend on version 2.x of the in-memory h2 database. Done by using MODE=LEGACY
=> Updated h2 to major release 2.x

bump-version.sh, lang-java-reach-soot/src/main/java/org/eclipse/steady/cg/soot/SootCallgraphConstructor.java, lang-python/src/main/java/org/eclipse/steady/python/Python335FileAnalyzer.java, lang-python/src/main/java/org/eclipse/steady/python/Python3FileAnalyzer.java, plugin-maven/pom.xml, pom.xml, rest-backend/pom.xml, rest-lib-utils/pom.xml, shared/src/test/java/org/eclipse/steady/shared/model/IExemptionTest.java
- Fixed the timezone offset in `bump-version.sh`, which caused some parsing problems down the line.
- Fixed calls of deprecated ANTLR APIs in `lang-python`.
- Updated minor and patch versions of several dependencies.
=> Updated deps, fixed bump-version.sh and deprec. API calls

kb-importer/pom.xml, pom.xml, rest-backend/pom.xml
Updated log4j to 2.17.2 , gson to 2.9.0, commons-io to 2.11.0 and json-path to 2.7.0
=> Updated log4j, gson and json-path

docker/push-images.sh, docs/public/content/admin/tutorials/build.md, docs/public/content/admin/tutorials/registry.md
Updated `push-images.sh`, which uploads Docker images to arbitrary registries, and related documentation
=> Updated push-images.sh and Docker-related documentation

lang-java-reach-soot/pom.xml, pom.xml
The deployment of module `plugin-gradle` did not consider the `.flattend-pom.xml` but the original `pom.xml`, which references the parent module. Since that is not deployed to Maven Central, the Gradle plugin did not work (also see #541).
=> Consider .flattened-pom.xml in plugin-gradle

pom.xml
OWASP CycloneDX is a lightweight Software Bill of Materials (SBOM) standard designed to use in the application security contexts and supply chain component analysis. CycloneDX is an OWASP flagship project ( [owasp.org/www-project-cyclonedx](https://owasp.org/www-project-cyclonedx) ). The Open Web Application Security Project is a non-profit foundation that works to improve the security of software. CycloneDX is already supported by many security vendors and projects ( [cyclonedx.org/about/supporters](https://cyclonedx.org/about/supporters) ). It is also recommended in the Technology Radar Volume 26 ( [thoughtworks.com/radar/platforms?blipid=202203034](https://www.thoughtworks.com/radar/platforms?blipid=202203034) )
More details about the plugin : …
=> Generate CycloneDX SBOM

lang/src/main/java/org/eclipse/steady/goals/GoalFactory.java, rest-backend/src/main/java/org/eclipse/steady/backend/util/PyPiVerifier.java, rest-backend/src/test/resources/pypi_flask.json, rest-lib-utils/src/main/java/org/eclipse/steady/cia/util/PypiWrapper.java
The cli scanner was still referencing the scan goal with the old package named "com.vulas.psr..". Now updated to org.eclipse.steady
=> updated reference to goal classes in cli-scanner

Jenkinsfile, pom.xml, rest-backend/pom.xml, rest-lib-utils/pom.xml
SBOM are not created during every build, but only if the `prepare-release` profile is enabled (formerly called `javadoc`). The `Jenkinsfile`has been adjusted accordingly. Finally, the `cyclonedx-maven-plugin` has also been added to the modules `rest-backend` and `rest-lib-utils`, and updated to version 2.7.1.
To test the SBOM generation for all 18 modules and the aggregator, run `mvn -DskipTests -Dspring.standalone clean install -P prepare-release,gradle`, and check whether the SBOM have been installed in the local M2 folder.
=> SBOM creation with prepare-release profile

README.md
Adjusted the README to focus on the analysis of Java apps, due to a number of analysis goals not being implemented for Python. Also removed the todo section, since the features mentioned are not actively developed.
=> Removed todo section and emphasized the use for Java apps

.gitignore, plugin-maven/src/main/java/org/eclipse/steady/java/mvn/MvnPluginInstr.java, shared/src/main/java/org/eclipse/steady/shared/util/FileUtil.java, shared/src/main/java/org/eclipse/steady/shared/util/VulasConfiguration.java, shared/src/test/java/org/eclipse/steady/shared/util/FileUtilTest.java
`FileUtil.copy`allows copying directories, which was not possible with the previous method `copyFile`.
=> Replaced FileUtil.copyFile by more generic FileUtil.copy

lang-java-reach-soot/src/main/java/org/eclipse/steady/cg/soot/SootCallgraphConstructor.java, lang-java/src/main/java/org/eclipse/steady/java/SpringBootAnalyzer.java, lang-java/src/main/java/org/eclipse/steady/java/WarAnalyzer.java, lang/src/main/java/org/eclipse/steady/goals/AbstractGoal.java
Java classes below `WEB-INF/classes` in a WAR and below `BOOT-INF/classes` in a Spring-Boot JAR are considered belonging to the application under analysis. For this reason, the digest of the WAR and JAR respectively will not be included in the instrumentation code. This digest should only be set for code in dependencies.
=> Removed digest from instr. code for classes in BOOT-INF/classes

README.md, docker/frontend-apps/Dockerfile, docker/frontend-bugs/Dockerfile, docker/kb-importer/Dockerfile, docker/patch-lib-analyzer/Dockerfile, docker/rest-backend/Dockerfile, docker/rest-lib-utils/Dockerfile
The advantage of using tags is that Docker fetches the image according to the architecture in place (provided it exists), rather than downloading the image pinned with the digest, which may not match to the architecture.
=> Use Docker tags instead of arch. specific digests

.travis/.env, cli-scanner/pom.xml, docker/.env.sample, docker/setup-steady.sh, docker/start-steady.sh, docs/mkdocs.yml, docs/public.properties, frontend-apps/pom.xml, frontend-bugs/pom.xml, kb-importer/pom.xml, lang-java-reach-soot/pom.xml, lang-java-reach-wala/pom.xml, lang-java-reach/pom.xml, lang-java/pom.xml, lang-python/pom.xml, lang/pom.xml, patch-analyzer/pom.xml, patch-lib-analyzer/pom.xml, plugin-gradle/pom.xml, plugin-maven/pom.xml, pom.xml, repo-client/pom.xml, rest-backend/pom.xml, rest-lib-utils/pom.xml, shared/pom.xml
=> Bump version to 3.2.5

docker/rest-backend/run.sh, rest-backend/src/main/java/org/eclipse/steady/backend/model/Library.java, rest-backend/src/main/java/org/eclipse/steady/backend/model/view/Views.java
The default view does not return the construct counters, which makes the mitigation tab fail.
Also added DEBUG_OPTS to backend's `run.sh` script, which can be specified in `docker-compose.yml` as follows (if debugging is needed).
```
ports:
- "8000:8000"
environment:
- DEBUG_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
```
=> Fixes a bug in the mitigation tab

shared/src/main/java/org/eclipse/steady/shared/util/VulasConfiguration.java
- environment variables were retrieved using System.getenv(); that returns an unmodifiebleMap thus raising an exception in windows that has `PROGRAMFILES(X86)` among its env variables 
- deletion of values raised ConcurrentModificationException 
Thanks @the-brownstone for reporting and highlighting the issues (see #583)
=> Processing of configurations raised issues in Windows
