.dockerignore
docker/Dockerfile
docker/README.md
docker/run.sh

This PR:
* generates the `.*ar`s in the `/docker/<component>` folders
* describes out testing environment

Feat: integrate copying of .jars

---

docker/frontend-apps/Dockerfile
docker/frontend-bugs/Dockerfile
docker/haproxy/Dockerfile
docker/patch-lib-analyzer/Dockerfile
docker/postgresql/Dockerfile
docker/rest-backend/Dockerfile
docker/rest-lib-utils/Dockerfile

chore(docker): update maintainer email

---

shared/src/main/java/com/sap/psr/vulas/shared/cache/Cache.java
shared/src/test/java/com/sap/psr/vulas/shared/cache/CacheTest.java

Fixed deletion of cache entries when maxSize==-1

---

rest-backend/src/main/java/com/sap/psr/vulas/backend/component/ApplicationExporterThread.java
rest-backend/src/test/java/com/sap/psr/vulas/backend/rest/ApplicationControllerTest.java

Use separator different from CSV column separator

rest-backend: Fixed output of multiple space owner emails

---

docker/.env.sample
docker/Dockerfile

- Installs Virtualenv
- Explicitly asks every key in the `.env` to be filled in

fix(docker): fix tests on Docker

---

docker/README.md
docker/run.sh

```sh
docker run -it --rm -v ${PWD}/docker:/exporter --env-file ./docker/.env -e "mvn_flags=-DexcludedGroups='com.sap.psr.vulas.shared.categories.Slow'" vulas-build-img
```

Custom mvn_flags

---

pom.xml

@Naramsim : Let's discuss this tomorrow

[WIP] Do not merge - Added variable for Gradle repo

---

lang/src/main/java/com/sap/psr/vulas/core/util/CoreConfiguration.java
lang/src/main/resources/vulas-core.properties
patch-analyzer/src/test/java/com/sap/psr/vulas/patcha/IT01_PatchAnalyzerIT.java
patch-lib-analyzer/src/main/resources/vulas-patch-lib-analyzer.properties
patch-lib-analyzer/src/test/java/CiaTest.java
plugin-maven/src/main/java/com/sap/psr/vulas/mvn/AbstractVulasMojo.java
plugin-maven/src/main/java/com/sap/psr/vulas/mvn/AbstractVulasSpaceMojo.java
plugin-maven/src/main/java/com/sap/psr/vulas/mvn/VulasAgentMojo.java
plugin-maven/src/main/resources/vulas-plugin-maven.properties
shared/src/main/java/com/sap/psr/vulas/shared/util/VulasConfiguration.java
shared/src/test/java/com/sap/psr/vulas/shared/util/VulasConfigurationTest.java

lang: Removed legacy config setting uploadEnabled

plugin-maven: Changed how-to configure prepare-vulas-agent

---

rest-lib-utils/src/main/java/com/sap/psr/vulas/cia/rest/ArtifactController.java
rest-lib-utils/src/test/java/com/sap/psr/vulas/cia/rest/IT01_ArtifactControllerTest.java
rest-lib-utils/src/test/java/com/sap/psr/vulas/cia/rest/IT02_SpringControllerTest.java

Intersect endpoint now returns 404 if cannot download

---

lang-java/src/test/java/com/sap/psr/vulas/java/JavaIdTest.java
lang/src/main/java/com/sap/psr/vulas/backend/BackendConnector.java
lang/src/main/java/com/sap/psr/vulas/report/Report.java
lang/src/main/resources/velocity_template.html
lang/src/main/resources/velocity_template.json
lang/src/main/resources/velocity_template.xml
shared/src/main/java/com/sap/psr/vulas/shared/connectivity/PathBuilder.java
shared/src/main/java/com/sap/psr/vulas/shared/util/StringList.java
shared/src/main/java/com/sap/psr/vulas/shared/util/StringUtil.java

Added warning about obsolete vuln. exemptions (in console and Html report)
Removed obsolete display of package info in Html, Xml and Json reports

Improved REPORT goal wrt. to obsolete exemptions

---

docs/public/content/vuln_db/index.md
lang-python/src/main/java/com/sap/psr/vulas/python/pip/PipWrapper.java
lang-python/src/test/java/com/sap/psr/vulas/python/pip/PipWrapperTest.java
lang-python/src/test/resources/pip-list-new.json
lang-python/src/test/resources/pip-list-old.json

More recent properties `installer` and `location` led to an exception

Fix the parsing of JSON output of pip list

---

docs/public/content/admin/tutorials/tutorial_vulndb.md
docs/public/content/vuln_db/tutorials/vuln_db_tutorial.md
docs/requirements.txt

Please wait until the script is in the kb before merging.

updated docs: added import of vuln kb and missing requirement

---

lang-python/src/main/java/com/sap/psr/vulas/python/PythonArchiveAnalyzer.java
lang/src/main/java/com/sap/psr/vulas/backend/BackendConnector.java
patch-lib-analyzer/pom.xml
patch-lib-analyzer/src/main/java/com/sap/psr/vulas/patcheval/utils/CSVHelper2.java
patch-lib-analyzer/src/main/java/com/sap/psr/vulas/patcheval/utils/PEConfiguration.java
patch-lib-analyzer/src/main/java/com/sap/psr/vulas/patcheval2/DigestAnalyzer.java
patch-lib-analyzer/src/main/java/com/sap/psr/vulas/patcheval2/LibraryAnalyzerThread2.java
patch-lib-analyzer/src/main/java/com/sap/psr/vulas/patcheval2/Main.java
patch-lib-analyzer/src/main/java/com/sap/psr/vulas/patcheval2/PE_Run.java
shared/src/main/java/com/sap/psr/vulas/shared/connectivity/PathBuilder.java
shared/src/main/java/com/sap/psr/vulas/shared/json/model/Artifact.java
shared/src/main/java/com/sap/psr/vulas/shared/util/FileUtil.java

Extended patch-lib-analyzer to compare digest for python constructs

Py patcheval

---

frontend-apps/src/main/webapp/model/Config.js
frontend-apps/src/main/webapp/view/Master.controller.js
rest-backend/src/main/resources/vulas-rest-backend.properties

Adds:
- `swid` validation on creation/managing of workspaces
- `swid` dynamic URL provided by `/backend`
- prevent Popover from closing when clicking outside of submitting invalid data

Validate swid/prevent Popover from closing

---

rest-backend/pom.xml
rest-backend/src/test/java/com/sap/psr/vulas/backend/util/PyPiVerifierTest.java
rest-lib-utils/pom.xml

Updated spring-boot-starter-web to 1.5.20 (in order to get a non-vulnerable version of Tomcat)

Updated spring boot starter web to 1.5.20

---

rest-backend/src/main/java/com/sap/psr/vulas/backend/component/ApplicationExporter.java
rest-backend/src/test/java/com/sap/psr/vulas/backend/component/ApplicationExporterTest.java

This bug occurred during the application export, and was related to the creation of partitions for the separate threads.

Fix bug related to creation of partitions

---

frontend-apps/src/main/webapp/model/Formatter.js
frontend-apps/src/main/webapp/view/Component.view.xml
rest-backend/src/main/java/com/sap/psr/vulas/backend/cve/CveReader2.java
rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/LibraryRepositoryImpl.java
rest-backend/src/main/java/com/sap/psr/vulas/backend/util/DigestVerifierEnumerator.java

Improved display of the timestamp on the dependencies tab.
Made sure that archive digests are verified even if there are no constructs.
Cache fetches CVEs even if they do not have CVSS scores (such that the description is read).

Improve timestamp display

---

rest-backend/src/main/java/com/sap/psr/vulas/backend/component/ApplicationExporter.java

When single export threads did not produce any result, the resulting JSON was malformed

Fix malformed JSON in app export

---

frontend-apps/src/main/webapp/model/Config.js
frontend-apps/src/main/webapp/view/Master.controller.js

Restore maintenance message if backend is down

---

lang-java/pom.xml
pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml

Updated jackson, httpclient, javassist, commons-lang

---

rest-backend/pom.xml
rest-lib-utils/pom.xml

Updated jackson and spring-boot-starter-parent

---

docs/mkdocs.yml
docs/public/content/admin/tutorials/docker.md
docs/public/content/admin/tutorials/index.md
docs/public/content/admin/tutorials/tutorial_vulndb.md
docs/public/content/index.md
docs/public/content/vuln_db/manuals/patch_analyzer.md
docs/public/content/vuln_db/tutorials/vuln_db_tutorial.md

Restructure devops docs

---

lang-java/src/main/java/com/sap/psr/vulas/java/ArchiveAnalysisManager.java
lang-java/src/main/java/com/sap/psr/vulas/java/JarAnalysisException.java
lang-java/src/main/java/com/sap/psr/vulas/java/JarAnalysisManager.java
lang-java/src/main/java/com/sap/psr/vulas/java/JarAnalyzer.java
lang-java/src/main/java/com/sap/psr/vulas/java/WarAnalyzer.java
lang-java/src/main/java/com/sap/psr/vulas/java/goals/InstrGoal.java
lang-java/src/main/java/com/sap/psr/vulas/java/tasks/JavaBomTask.java
lang-java/src/main/java/com/sap/psr/vulas/monitor/trace/TraceCollector.java
lang-java/src/main/resources/vulas-java.properties
lang-java/src/test/java/com/sap/psr/vulas/java/JarAnalysisManagerTest.java
lang-java/src/test/java/com/sap/psr/vulas/java/JarAnalyzerTest.java
lang-java/src/test/java/com/sap/psr/vulas/java/WarAnalyzerTest.java
lang/src/main/java/com/sap/psr/vulas/core/util/CoreConfiguration.java

Jar and WarAnalyzer implement Callable rather than Runnable

---

docs/public/content/about/index.md
docs/public/content/admin/tutorials/docker.md
docs/public/content/admin/tutorials/registry.md
docs/public/content/index.md
docs/public/content/user/index.md
docs/public/content/user/manuals/analysis.md
docs/public/content/user/manuals/frontend.md
docs/public/content/user/manuals/setup.md
docs/public/content/user/support/index.md
docs/public/content/user/tutorials/index.md
docs/public/content/user/tutorials/java_cli.md
docs/public/content/user/tutorials/java_gradle.md
docs/public/content/user/tutorials/java_maven.md
docs/public/content/user/tutorials/java_maven_advanced.md
docs/public/content/user/tutorials/python_cli.md
docs/public/content/user/tutorials/workspace_howto.md
docs/public/content/vuln_db/index.md
docs/public/content/vuln_db/manuals/index.md
docs/public/content/vuln_db/tutorials/vuln_db_tutorial.md

Add trailing slash to internal links

---

docs/public/content/css/override.css
docs/public/content/user/index.md

Fix docs' CSS for mobile devices

---

frontend-apps/src/main/webapp/index.html
frontend-apps/src/main/webapp/model/Config.js
frontend-apps/src/main/webapp/view/BugDetail.controller.js
frontend-apps/src/main/webapp/view/BugDetail.view.xml
frontend-apps/src/main/webapp/view/Component.controller.js
frontend-apps/src/main/webapp/view/Component.view.xml

- Fix search
- Enable cache fetching
- Fix a link that brings from BugDetails to ArchiveDetails
- Load Google Trends with `defer` instead of `async` to prevent loading the library after `DOMContentLoaded`
- Check models existance before `destroy`ing them

Frontend-apps improvements

---

docs/public/content/user/manuals/analysis.md

Simplified doc related to Soot reachability analysis

---

cli-scanner/pom.xml
lang-java-reach-soot/pom.xml
plugin-gradle/pom.xml
plugin-maven/pom.xml

Excluded jasmin from Soot, and scoped Soot back to runtime

---

lang-java-reach-soot/pom.xml

Also exclude Jasmin from InfoFlow

---

frontend-apps/src/main/webapp/model/Formatter.js
frontend-apps/src/main/webapp/view/Component.controller.js

Show average dependency age in months (rather than days)

---

docker/push-images.sh
docs/public/content/admin/tutorials/docker.md

Publish the generator image to Docker registries

---

rest-lib-utils/src/main/java/com/sap/psr/vulas/cia/rest/ArtifactController.java

Removed the now unused header X-Vulas-Echo from rest-lib-utils

removed echo header from ArtifactController

---

frontend-apps/src/main/webapp/css/style.css
frontend-apps/src/main/webapp/view/ArchiveDetail.view.xml
frontend-apps/src/main/webapp/view/Component.controller.js
frontend-apps/src/main/webapp/view/Component.view.xml

Add cursor pointer to cells and add vertical padding to cells

---

.travis/check.sh
docker/cache/nginx.conf
docker/docker-compose.yml
docker/haproxy/conf/haproxy.cfg

- Restarts automatically the containers
- Add cache for `?lastChanged=\d{20}` requests

Docker restart policy and cache

---

pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml

Update jackson-databind from 2.9.9 to 2.9.9.1

update version for jackson-databind

---

rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/ApplicationRepositoryImpl.java
shared/src/main/java/com/sap/psr/vulas/shared/json/model/diff/JarDiffResult.java

fix get bug details and updatemetrics
- [x ] Tests

fix remaining exceptions

---

frontend-apps/src/main/webapp/view/Component.controller.js
frontend-apps/src/main/webapp/view/Component.view.xml

Prevent frontend reload when 'advanced' columns are shown

---

plugin-maven/pom.xml
pom.xml

Updated wagon-file, httpclient, and, plexus-utils and maven-* dependencies

---

.gitignore
frontend-bugs/src/main/webapp/css/style.css
frontend-bugs/src/main/webapp/index.html
frontend-bugs/src/main/webapp/view/Component.controller.js
frontend-bugs/src/main/webapp/view/Component.view.xml

Load CVEs asynchronously

---

patch-lib-analyzer/src/main/java/com/sap/psr/vulas/patcheval/representation/ArtifactResult2.java
shared/src/main/java/com/sap/psr/vulas/shared/json/model/Version.java

Fixed version comparison to only compare numeric versions if numbers exists

compare version numbers if numbers exists

---

pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml

Updated jackson-databind to 2.9.9.2

Updated jackson-databind to 2.9.9.2

---

rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/AffectedLibraryRepositoryImpl.java

check if libraryId exists before looking for affected libraries

---

.travis.yml
docker/push-images.sh

Enable Travis to push Docker images on Docker Hub

---

docker/frontend-bugs/Dockerfile

Install bugs in JETTY_BASE in Docker

---

.travis.yml
.travis/check_dockerfile_location.sh

After releasing our images to Docker Hub we should make sure not to change the Internet URL where the sources can be found.

Dockerfile sources check

---

docs/public/content/user/tutorials/jenkins_howto.md
pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml

Updated jackson-databind to 2.9.9.3, httpclient to 4.5.9 and commons-beanutils to 1.9.4

Updated httpclient, jackson-databind and commons-beanutils

---

.travis.yml
pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml

Added profile `javadoc`, which creates the Javadoc for all Java sources as well as the `sources` artifact.
Added profile `release`, which PGP signs the artifacts and releases on Central

Change pom.xml to release on Maven Central

---

pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml

Updated to httpclient 4.5.10, commons-compress 1.19, spring-boot-starter-parent 1.5.22.RELEASE and commons-beanutils 1.9.4

Updated httpclient, commons-compress and spring-boot-starter-parent

---

.travis.yml

Separate Javadoc check from JUnit tests

---

plugin-maven/pom.xml
pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml

Updated jackson-* and ant

---

.travis.yml
.travis/.env
.travis/docker_hub_push_release.sh
.travis/docker_hub_push_snapshot.sh
.travis/skaffold.yaml

Add jib through skaffold

---

.travis.yml
.travis/docker_hub_push_release.sh
.travis/docker_hub_push_snapshot.sh

Move skaffold to OpenJDK travis block

---

docker/docker-compose.build.yml
docker/patch-analyzer/Dockerfile
docker/run.sh
patch-analyzer/src/main/java/com/sap/psr/vulas/patcha/PatchAnalyzer.java

Create patch-analyzer Docker image

---

.travis/check.sh
docker/docker-compose.build.yml
docker/patch-analyzer/Dockerfile
docker/push-images.sh
docker/run.sh
patch-analyzer/src/main/java/com/sap/psr/vulas/patcha/PatchAnalyzer.java

Push patch-analyzer image to Docker Hub

---

frontend-apps/pom.xml
frontend-bugs/pom.xml
patch-analyzer/pom.xml
patch-lib-analyzer/pom.xml
pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml

The target repo for snapshots can be specified via `-Dsnapshots.repo=`.

Allow flexible deployment of snapshots (to different repos)

---

pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml

Updated to jackson-databind:2.9.10.1

---

docs/public/content/admin/tutorials/helm.md

Fix broken links for helm docs

---

rest-backend/src/main/java/com/sap/psr/vulas/backend/rest/CveController.java
rest-backend/src/test/java/com/sap/psr/vulas/backend/cve/CveReader2Test.java
rest-backend/src/test/resources/cves/CVE-2019-0047-schema1.1.json

Added JUnit test to check that CVSS scores v3.1 are properly read by `CveReader2`.

Added test to check whether CVSS 3.1 scores are properly read

---

docs/mkdocs.yml
docs/public/content/admin/index.md

Add k8s resources info page to the index

---

pom.xml

Updated junit to 4.13 and wagon-file to 3.3.4

---

docs/mkdocs.yml
docs/public.properties
docs/public/content/index.md

Updated all docs to reflect the renaming to Eclipse Steady

Updated docs for Eclipse Steady

---

pom.xml

Updated references in `pom.xml`

Updated pom.xml to reflect repo move

---

docs/public/content/user/manuals/analysis.md

Improved documentation related to the CLEAN goal.

Updated doc related to CLEAN goal

---

docker/rest-backend/conf/restbackend.properties

Fixed environment variables that were causing the issue on macOS.

Fixes https://github.com/eclipse/steady/issues/348

---

plugin-maven/pom.xml
pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml

Minor updates of
- jackson-databind
- httpclient
- commons-compress
- maven-*

Minor updates of jackson-databind, httpclient and a few other dependencies

---

.travis/check.sh
.travis/check_dockerfile_location.sh
docker/docker-compose.build.yml
docker/docker-compose.yml
docker/haproxy/conf/haproxy.cfg
docker/push-images.sh
rest-nvd/docker-compose.yml

integrate rest-nvd

---

rest-nvd/README.md
rest-nvd/app/main.py

For HAProxy configuration we would need a prefix url. With this PR I have added nvd as the prefix url for all rest-nvd requests.

prefix rest-nvd url

---

docker/docker-compose.yml
docker/haproxy/conf/haproxy.cfg
rest-nvd/docker-compose.override.yml
rest-nvd/docker-compose.yml

Signed-off-by: Sumeet Patil <sumeet.patil@sap.com>

Fix haproxy and docker configurations for rest-nvd

---

docs/public/content/about/index.md
docs/public/content/user/manuals/assess_and_mitigate.md

OWASP recently updated their website. Some links in our docs were broken.

Update OWASP links

---

docs/public/content/about/index.md

Updated contributors in documentation

Updated contributors in documentation

---

rest-backend/src/main/java/com/sap/psr/vulas/backend/repo/AffectedLibraryRepository.java
rest-backend/src/main/java/com/sap/psr/vulas/backend/rest/BugController.java
rest-backend/src/test/java/com/sap/psr/vulas/backend/rest/BugControllerTest.java

Added endpoint to the BugController to retrieve affected libraries for given group and artifact (and optionally a defined source).

added endpoint to get affectedLibraries by group and artifact

---

.travis.yml

Automate docs release

---

.travis.yml
.travis/package_steady_cli.sh
.travis/vulas-custom.properties.sample

Automate Cli Release

---

.travis/package_steady_cli.sh

Tag release check for CLI release

---

docker/README.md

Link to new Eclipse GH pages

---

docs/public/content/vuln_db/index.md

Changed references to sap/vulnerability-assessment-kb to refer to sap/project-kb instead

updated references to project KB

---

pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml

Updated several dependencies to latest, non-vulnerable versions

Updated PostgreSQL, Jackson and Hibernate dependencies

---

docs/public/content/user/support/faq.md
rest-backend/pom.xml
rest-lib-utils/pom.xml

Updated tomcat-embed-* to 8.5.57

Updated tomcat-embed-* to 8.5.57

---

rest-backend/pom.xml
rest-lib-utils/pom.xml

Removal and update of comments, and removal of rest-lib-util's dependency on hamcrest-all

Some cleanup of pom.xml files in rest-backend and rest-lib-utils

---

kb-importer/pom.xml
kb-importer/src/main/java/com/sap/psr/vulas/kb/task/ImportVulnerability.java
lang/src/main/java/com/sap/psr/vulas/backend/BackendConnector.java

Handle multiple descriptions

---

frontend-bugs/src/main/webapp/model/Formatter.js
frontend-bugs/src/main/webapp/view/Component.controller.js
frontend-bugs/src/main/webapp/view/Component.view.xml

UI changes for Kaybee Assessment

---

kb-importer/src/main/java/org/eclipse/steady/kb/command/CommandExecutor.java
kb-importer/src/main/java/org/eclipse/steady/kb/task/ImportVulnerability.java

kb-impoter fix for relative url and escape string for description

---

pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml

Updated jackson-databind to 2.9.10.6 and snakeyaml to 1.26

Updated jackson-databind to 2.9.10.6 and snakeyaml to 1.26

---

rest-backend/src/main/java/org/eclipse/steady/backend/repo/ApplicationRepositoryImpl.java
rest-backend/src/test/java/org/eclipse/steady/backend/rest/ApplicationControllerTest.java

Fix remaining bug in order to consider affected libraries from both digests and gavs in case of vulnerability with origin BUNDLEDAFFLIBID

Fix bundledafflibids

---

README.md
docker/push-images.sh
docs/public/content/admin/tutorials/docker.md
docs/public/content/admin/tutorials/helm.md
docs/public/content/admin/tutorials/kustomize.md
docs/public/content/admin/tutorials/registry.md
docs/public/content/user/support/index.md
kubernetes/helm/vulnerability-assessment-tool-admin/Chart.yaml
kubernetes/helm/vulnerability-assessment-tool-admin/charts/nginx-ingress/Chart.yaml
kubernetes/helm/vulnerability-assessment-tool-core/Chart.yaml
kubernetes/helm/vulnerability-assessment-tool-core/charts/database/Chart.yaml
kubernetes/helm/vulnerability-assessment-tool-core/charts/frontendapps/Chart.yaml
kubernetes/helm/vulnerability-assessment-tool-core/charts/frontendbugs/Chart.yaml
kubernetes/helm/vulnerability-assessment-tool-core/charts/patchlibanalyzer/Chart.yaml
kubernetes/helm/vulnerability-assessment-tool-core/charts/restbackend/Chart.yaml
kubernetes/helm/vulnerability-assessment-tool-core/charts/restlibutils/Chart.yaml
kubernetes/helm/vulnerability-assessment-tool-monitoring/Chart.yaml
kubernetes/helm/vulnerability-assessment-tool-monitoring/charts/elastic/Chart.yaml
kubernetes/helm/vulnerability-assessment-tool-monitoring/charts/fluentd/Chart.yaml
kubernetes/helm/vulnerability-assessment-tool-monitoring/charts/grafana/Chart.yaml
kubernetes/helm/vulnerability-assessment-tool-monitoring/charts/prometheus/Chart.yaml

Changed the links to Steady

---

lang-python/src/main/java/org/eclipse/steady/python/sign/PythonConstructDigestDeserializer.java
lang-python/src/main/java/org/eclipse/steady/python/sign/PythonConstructDigestSerializer.java
patch-lib-analyzer/src/main/java/org/eclipse/steady/patcheval/ByteCodeComparator.java
patch-lib-analyzer/src/main/java/org/eclipse/steady/patcheval/LibraryAnalyzerThread2.java
shared/src/main/java/org/eclipse/steady/shared/enums/DigestAlgorithm.java

Fixed typo in json for `PythonConstructDigest` (was serializing `digestAlgorihtm` and added custom deserializer, used in patch-lib-analyzer to get signature for Python constructs)

Python custom deserializer

---

.travis.yml

use Travis' `travis_retry` when checking the docs

Use Travis' travis_retry for checking the docs

---

rest-lib-utils/pom.xml

Updated ant from 1.10.8 to 1.10.9

Updated ant from 1.10.8 to 1.10.9

---

pom.xml

Upgrade Junit due to a security vulnerability - https://github.com/junit-team/junit4/security/advisories/GHSA-269g-pwp5-87pp

Bump junit from 4.13 to 4.13.1

---

set-version.sh

Added license and copyright header

Added license and copyright header

---

.travis/check.sh
docker/.env.sample
docker/docker-compose.build.yml
docker/docker-compose.yml
docker/kb-importer/Dockerfile
docker/kb-importer/certs/readme.txt
docker/kb-importer/conf/kaybeeconf-initial.yaml
docker/kb-importer/conf/kaybeeconf.yaml
docker/kb-importer/kb-importer.sh
docker/kb-importer/start.sh
docker/push-images.sh
docker/run.sh

kb-importer docker setup

---

pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml

Updated httpclient and hibernate

Updated httpclient and hibernate

---

pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml

Updated tomcat and jackson-databind

Updated tomcat and jackson-databind

---

pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml

Updated Jackson to the latest non-vulnerable version

Updated Jackson

---

rest-backend/pom.xml
rest-lib-utils/pom.xml

Updated tomcat to 8.5.63

---

README.md

Added acknowledgment of project Sparta

Added acknowledgment

---

lang-java-reach-soot/pom.xml
lang-java/pom.xml
rest-lib-utils/pom.xml

Updated Guava from 27 to 30

---

.pipeline/config.yml
.travis.yml
.travis/check.sh
Jenkinsfile
docker/pipeline/Dockerfile
docker/pipeline/README.md
docker/push-images.sh
rest-backend/pom.xml
rest-backend/src/test/java/org/eclipse/steady/backend/rest/HubIntegrationControllerTest.java

Build and release Steady in Jenkins pipeline

---

pom.xml

Updated antlr4-runtime, javassist, log4j and junit

Updated antlr4-runtime, javassist, log4j and junit

---

.reuse/dep5
pom.xml
rest-lib-utils/pom.xml

Updated commons-io to 2.7 and fixed compliance with REUSE

---

plugin-maven/pom.xml
pom.xml

Updated org.apache.maven to 3.8.1

---

.reuse/dep5
Jenkinsfile
cli-scanner/pom.xml
lang-java-reach-soot/pom.xml
lang-java-reach-wala/pom.xml
lang-java-reach/pom.xml
lang-java/pom.xml
lang-python/pom.xml
lang/pom.xml
plugin-gradle/pom.xml
plugin-maven/pom.xml
shared/pom.xml

Fixed the description in several `pom.xml` files

Fix description of Maven modules

---

.travis/.env
cli-scanner/pom.xml
frontend-apps/pom.xml
frontend-bugs/pom.xml
kb-importer/pom.xml
kubernetes/helm/vulnerability-assessment-tool-core/charts/frontendbugs/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/patchlibanalyzer/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/restbackend/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/restlibutils/README.md
lang-java-reach-soot/pom.xml
lang-java-reach-wala/pom.xml
lang-java-reach/pom.xml
lang-java/pom.xml
lang-python/pom.xml
lang/pom.xml
patch-analyzer/pom.xml
patch-lib-analyzer/pom.xml
plugin-gradle/pom.xml
plugin-maven/pom.xml
pom.xml
repo-client/pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml
shared/pom.xml

Bumped version to 3.2.1-SNAPSHOT

---

Jenkinsfile
docker/pipeline/Dockerfile

Updated the Jenkins pipeline to run a REUSE compliance check (and break the job in case of non-compliance)

Added REUSE compliance check

---

pom.xml
rest-backend/pom.xml

Updated commons-compress from 1.20 to 1.21

---

.travis/.env
cli-scanner/pom.xml
docker/setup-steady.sh
docker/start-steady.sh
docs/mkdocs.yml
docs/public.properties
frontend-apps/pom.xml
frontend-bugs/pom.xml
kb-importer/pom.xml
kubernetes/helm/vulnerability-assessment-tool-core/charts/frontendbugs/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/patchlibanalyzer/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/restbackend/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/restlibutils/README.md
lang-java-reach-soot/pom.xml
lang-java-reach-wala/pom.xml
lang-java-reach/pom.xml
lang-java/pom.xml
lang-python/pom.xml
lang/pom.xml
patch-analyzer/pom.xml
patch-lib-analyzer/pom.xml
plugin-gradle/pom.xml
plugin-maven/pom.xml
pom.xml
repo-client/pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml
shared/pom.xml

Bump version from 3.2.1-SNAPSHOT to 3.2.1, ready for release

Bumped version to 3.2.1

---

pom.xml

Fixed timestamp format to make it parsable

Fix timestamp format

---

docs/requirements.txt

Updated mkdocs from 1.0.3 to 1.2.3

Updated mkdocs

---

pom.xml

Updated log4j from 2.16.0 to 2.17.0

---

.travis/.env
cli-scanner/pom.xml
docker/setup-steady.sh
docker/start-steady.sh
docs/mkdocs.yml
docs/public.properties
frontend-apps/pom.xml
frontend-bugs/pom.xml
kb-importer/pom.xml
kubernetes/helm/vulnerability-assessment-tool-core/charts/frontendbugs/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/patchlibanalyzer/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/restbackend/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/restlibutils/README.md
lang-java-reach-soot/pom.xml
lang-java-reach-wala/pom.xml
lang-java-reach/pom.xml
lang-java/pom.xml
lang-python/pom.xml
lang/pom.xml
patch-analyzer/pom.xml
patch-lib-analyzer/pom.xml
plugin-gradle/pom.xml
plugin-maven/pom.xml
pom.xml
repo-client/pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml
shared/pom.xml

Bumped version to 3.2.2

---

.travis/.env
cli-scanner/pom.xml
docker/.env.sample
frontend-apps/pom.xml
frontend-bugs/pom.xml
kb-importer/pom.xml
kubernetes/helm/vulnerability-assessment-tool-core/charts/frontendbugs/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/patchlibanalyzer/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/restbackend/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/restlibutils/README.md
lang-java-reach-soot/pom.xml
lang-java-reach-wala/pom.xml
lang-java-reach/pom.xml
lang-java/pom.xml
lang-python/pom.xml
lang/pom.xml
patch-analyzer/pom.xml
patch-lib-analyzer/pom.xml
plugin-gradle/pom.xml
plugin-maven/pom.xml
pom.xml
repo-client/pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml
shared/pom.xml

Bumped version to 3.2.3-SNAPSHOT

---

rest-backend/pom.xml

Update org.postgresql:postgresql  to version  42.2.25

Update postgres to 42.2.25

---

rest-backend/pom.xml
rest-lib-utils/pom.xml

Updated springboot

---

.travis/.env
cli-scanner/pom.xml
docker/.env.sample
docker/setup-steady.sh
docker/start-steady.sh
docs/mkdocs.yml
docs/public.properties
frontend-apps/pom.xml
frontend-bugs/pom.xml
kb-importer/pom.xml
lang-java-reach-soot/pom.xml
lang-java-reach-wala/pom.xml
lang-java-reach/pom.xml
lang-java/pom.xml
lang-python/pom.xml
lang-python/src/test/java/org/eclipse/steady/python/virtualenv/VirtualenvWrapperTest.java
lang/pom.xml
patch-analyzer/pom.xml
patch-lib-analyzer/pom.xml
plugin-gradle/pom.xml
plugin-maven/pom.xml
pom.xml
repo-client/pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml
shared/pom.xml

Bumped version to 3.2.3 to be released

Bump version to 3.2.3

---

.travis/.env
cli-scanner/pom.xml
frontend-apps/pom.xml
frontend-bugs/pom.xml
kb-importer/pom.xml
kubernetes/helm/vulnerability-assessment-tool-core/charts/frontendbugs/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/patchlibanalyzer/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/restbackend/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/restlibutils/README.md
lang-java-reach-soot/pom.xml
lang-java-reach-wala/pom.xml
lang-java-reach/pom.xml
lang-java/pom.xml
lang-python/pom.xml
lang/pom.xml
patch-analyzer/pom.xml
patch-lib-analyzer/pom.xml
plugin-gradle/pom.xml
plugin-maven/pom.xml
pom.xml
repo-client/pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml
shared/pom.xml

Bumped version to 3.2.4-SNAPSHOT

bumped version to 3.2.4-SNAPSHOT

---

.travis/.env
cli-scanner/pom.xml
frontend-apps/pom.xml
frontend-bugs/pom.xml
kb-importer/pom.xml
kubernetes/helm/vulnerability-assessment-tool-core/charts/frontendbugs/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/patchlibanalyzer/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/restbackend/README.md
kubernetes/helm/vulnerability-assessment-tool-core/charts/restlibutils/README.md
lang-java-reach-soot/pom.xml
lang-java-reach-wala/pom.xml
lang-java-reach/pom.xml
lang-java/pom.xml
lang-python/pom.xml
lang/pom.xml
patch-analyzer/pom.xml
patch-lib-analyzer/pom.xml
plugin-gradle/pom.xml
plugin-maven/pom.xml
pom.xml
repo-client/pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml
shared/pom.xml

bump version to 3.2.5-SNAPSHOT

bump version to 3.2.5-SNAPSHOT

---

README.md

Added details about the systems where the setup/start scripts have been tested

Added details as to where the setup/start scripts have been tested

---

README.md

Added a disclaimer to the README explaining current limitations and particularities of Steady.
Also updated the history section of the README, reflecting that Steady is no more used productively at SAP.

Added disclaimer and updated history in README

---

.travis/.env
cli-scanner/pom.xml
frontend-apps/pom.xml
frontend-bugs/pom.xml
kb-importer/pom.xml
lang-java-reach-soot/pom.xml
lang-java-reach-wala/pom.xml
lang-java-reach/pom.xml
lang-java/pom.xml
lang-python/pom.xml
lang/pom.xml
patch-analyzer/pom.xml
patch-lib-analyzer/pom.xml
plugin-gradle/pom.xml
plugin-maven/pom.xml
pom.xml
repo-client/pom.xml
rest-backend/pom.xml
rest-lib-utils/pom.xml
shared/pom.xml

Bump to 3.2.6-SNAPSHOT
